baseURL = '(website url)'
languageCode = 'en-us'
title = 'New Website'
theme = 'blog_simple'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 40

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 50
