baseURL = 'https://v01p3.com/'
languageCode = 'en-us'
title = 'New Website'
theme = 'blog_simple'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 40

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 50

[outputs]
    home = ["html"]

[module]
    [module.hugoVersion]
        min = "0.128.0"
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "content"
        target = "content"
    [[module.mounts]]
        source       = "hugo_stats.json"
        target       = "assets/notwatching/hugo_stats.json"
        disableWatch = true
[build.buildStats]
    enable = true
[[build.cachebusters]]
    source = "assets/notwatching/hugo_stats\\.json"
    target = "css"
[[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"

[markup]
    [markup.highlight]
        style = 'github'
