name = 'blog_simple'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Simple theme for blogging sites'

tags = ['blog', 'simple', 'starter']

[author]
  name = 'v01p3'
  homepage = 'https://github.com/v01p3'
